'use client'
import {useEffect,useState} from 'react'
import {useParams} from 'next/navigation'
import {createClient} from '@/lib/supabase/client'

type Quote={id:string,title:string,customer_name:string,customer_email:string|null,notes:string|null,status:string,subtotal:number,tax:number,total:number,valid_until:string|null,viewed_at:string|null}
type Item={id:string,description:string,quantity:number,unit_price:number,total:number}
export default function PublicQuote(){const {token}=useParams<{token:string}>();const supabase=createClient();const[q,setQ]=useState<Quote|null>(null),[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[done,setDone]=useState('')
useEffect(()=>{(async()=>{const r=await supabase.from('quotes').select('*').eq('token',token).single();if(r.data){setQ(r.data);const i=await supabase.from('quote_items').select('*').eq('quote_id',r.data.id);setItems(i.data||[]);if(!r.data.viewed_at)await supabase.from('quotes').update({viewed_at:new Date().toISOString(),status:r.data.status==='draft'?'sent':r.data.status}).eq('id',r.data.id)}})().finally(()=>setLoading(false))},[token])
async function respond(status:string){setBusy(true);const r=await supabase.rpc('respond_to_quote',{p_token:token,p_status:status});if(!r.error){setQ(r.data);setDone(status==='accepted'?'Quote accepted. We’ll be in touch with next steps.':'Quote declined.');}else setDone(r.error.message);setBusy(false)}
if(loading)return <main className="publicQuote"><div className="quoteCard">Loading quote…</div></main>;if(!q)return <main className="publicQuote"><div className="quoteCard"><h1>Quote not found.</h1><p>This link may have expired or is no longer available.</p></div></main>
return <main className="publicQuote"><div className="quoteCard"><div className="quoteBrand">quote<span>flow</span></div><div className="quoteTop"><div><small>PROJECT QUOTE</small><h1>{q.title}</h1><p>Prepared for {q.customer_name}</p></div><div className="quoteStatus">{q.status}</div></div><div className="quoteItems">{items.map(i=><div className="quoteLine" key={i.id}><span>{i.description} × {i.quantity}</span><b>${Number(i.total).toLocaleString(undefined,{minimumFractionDigits:2})}</b></div>)}</div><div className="quoteTotals"><span>Subtotal</span><b>${Number(q.subtotal).toLocaleString(undefined,{minimumFractionDigits:2})}</b><span>Tax</span><b>${Number(q.tax).toLocaleString(undefined,{minimumFractionDigits:2})}</b><strong>Total</strong><strong>${Number(q.total).toLocaleString(undefined,{minimumFractionDigits:2})}</strong></div>{q.notes&&<div className="quoteNotes"><small>NOTES</small><p>{q.notes}</p></div>}{done?<div className="quoteDone">{done}</div>:q.status!=='accepted'&&q.status!=='declined'&&<div className="quoteActions"><button onClick={()=>respond('declined')} disabled={busy}>Decline</button><button onClick={()=>respond('accepted')} disabled={busy}>Accept quote →</button></div>}<p className="quoteFine">Powered by QuoteFlow</p></div></main>}
