'use client'
import {useEffect,useState} from 'react'
import {useRouter,useSearchParams} from 'next/navigation'
import {createClient} from '@/lib/supabase/client'
export default function AuthPage(){
 const router=useRouter(),params=useSearchParams(),supabase=createClient(); const [mode,setMode]=useState(params.get('mode')==='signin'?'signin':'signup'); const [name,setName]=useState(''),[business,setBusiness]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false)
 useEffect(()=>setMode(params.get('mode')==='signin'?'signin':'signup'),[params])
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setLoading(true); if(mode==='signup'){const r=await supabase.auth.signUp({email,password,options:{data:{full_name:name,business_name:business}}});if(r.error){setError(r.error.message);setLoading(false);return}}else{const r=await supabase.auth.signInWithPassword({email,password});if(r.error){setError(r.error.message);setLoading(false);return}} router.push('/dashboard');router.refresh()}
 return <main className="authPage"><div className="authPanel"><a className="brand" href="/">quote<span>flow</span></a><div className="authCopy"><small>{mode==='signin'?'WELCOME BACK':'START FREE'}</small><h1>{mode==='signin'?'Welcome back.':'Create your workspace.'}</h1><p>{mode==='signin'?'Sign in to pick up where you left off.':'Set up your QuoteFlow workspace and start organizing your pipeline.'}</p></div><form onSubmit={submit}>{mode==='signup'&&<><label>Your name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Alex Smith"/></label><label>Business name<input required value={business} onChange={e=>setBusiness(e.target.value)} placeholder="Smith Roofing"/></label></>}<label>Work email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@yourbusiness.com"/></label><label>Password<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/></label>{error&&<div className="authError">{error}</div>}<button disabled={loading} className="btn primary authSubmit">{loading?'Working…':mode==='signin'?'Sign in →':'Create my account →'}</button></form><div className="authSwitch">{mode==='signin'?"Don't have an account?":"Already have an account?"} <button onClick={()=>setMode(mode==='signin'?'signup':'signin')}>{mode==='signin'?'Start free':'Welcome back'}</button></div><div className="authFine">14-day trial billing is configured in Stripe when your production price is connected.</div></div></main>
}
