'use client'
import { useState } from 'react'

const leads=[['Sarah Mitchell','Roof repair','2 min ago','$4,850'],['Mike Johnson','AC replacement','18 min ago','$7,200'],['Olivia Carter','Kitchen remodel','42 min ago','$12,400']]

export default function Home(){
 const [email,setEmail]=useState(''); const [sent,setSent]=useState(false)
 return <main>
  <nav className="shell nav"><div className="brand">quote<span>flow</span></div><div className="navlinks"><a href="#product">Product</a><a href="#pricing">Pricing</a><a href="#demo">Demo</a></div><button className="btn primary" onClick={()=>document.getElementById('pricing')?.scrollIntoView()}>Start free</button></nav>
  <section className="hero shell"><div className="eyebrow">BUILT FOR LOCAL SERVICE BUSINESSES</div><h1>Turn a new lead into a <em>signed job.</em></h1><p>QuoteFlow gives contractors a faster way to send professional estimates, capture approvals, and keep every lead moving—without the spreadsheet chaos.</p><div className="actions"><button className="btn primary" onClick={()=>document.getElementById('pricing')?.scrollIntoView()}>Get QuoteFlow →</button><button className="btn ghost" onClick={()=>document.getElementById('demo')?.scrollIntoView()}>See the dashboard</button></div><div className="proof"><span>✓ Instant estimates</span><span>✓ Approval tracking</span><span>✓ Lead pipeline</span></div></section>
  <section id="product" className="shell grid"><div className="card"><h3>⚡ Quote in seconds</h3><p>Build reusable services and pricing. Create a polished estimate without opening a spreadsheet.</p></div><div className="card"><h3>✍️ Get the yes</h3><p>Customers see one clean quote page with the price, scope, options, and a clear approval action.</p></div><div className="card"><h3>📈 Never lose a lead</h3><p>See every inquiry, estimate, approval, and follow-up in one simple pipeline.</p></div></section>
  <section id="demo" className="shell"><div className="dash"><div className="dashbar"><b>QuoteFlow</b><button className="btn primary">+ New quote</button></div><div className="dashbody"><aside className="side"><div className="active">Overview</div><div>Leads</div><div>Quotes</div><div>Services</div><div>Settings</div></aside><div className="main"><h2>Good morning 👋</h2><p style={{color:'#829189'}}>Here’s what is happening with your pipeline.</p><div className="stats"><div className="stat"><small>Open leads</small><b>24</b></div><div className="stat"><small>Quotes sent</small><b>18</b></div><div className="stat"><small>Won this month</small><b>$31.4k</b></div></div><div className="lead"><div className="leadrow" style={{color:'#718078'}}><div>LEAD</div><div>STATUS</div><div>VALUE</div><div></div></div>{leads.map((l,i)=><div className="leadrow" key={i}><div><b>{l[0]}</b><br/><span style={{color:'#718078'}}>{l[1]}</span></div><div><span className="pill">{i===0?'New lead':i===1?'Quote sent':'Approved'}</span></div><div>{l[3]}</div><div>•••</div></div>)}</div></div></div></div></section>
  <section id="pricing" className="shell" style={{padding:'60px 0'}}><div className="card" style={{maxWidth:650,margin:'auto',textAlign:'center'}}><div className="eyebrow">SIMPLE PRICING</div><h2 style={{fontSize:42,margin:'18px 0 8px'}}>Stop losing $5k jobs.</h2><p>Everything you need to turn more inquiries into booked work.</p><div className="price">$79<span>/month</span></div><p style={{fontSize:13}}>One plan. Unlimited quotes. Unlimited leads.</p><button className="btn primary" style={{width:'100%',marginTop:12}} onClick={()=>setSent(true)}>{sent?'Check your email ✓':'Start your 14-day free trial →'}</button><p style={{fontSize:12,marginTop:12}}>No credit card required to start.</p></div></section>
  <section className="shell" style={{padding:'10px 0 70px',textAlign:'center'}}><h2>Built to pay for itself.</h2><p style={{color:'#91a097'}}>One additional booked job can cover months of QuoteFlow.</p><form onSubmit={e=>{e.preventDefault();setSent(true)}} style={{display:'flex',maxWidth:520,margin:'22px auto',gap:8}}><input aria-label="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" style={{flex:1,padding:14,borderRadius:12,border:'1px solid #294035',background:'#0b1712',color:'white'}}/><button className="btn primary">{sent?'You’re in ✓':'Join the launch list'}</button></form></section>
  <footer className="shell footer"><b>quoteflow</b> — close more jobs, faster. © 2026</footer>
 </main>
}
