create extension if not exists pgcrypto;

create table if not exists public.businesses (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null unique references auth.users(id) on delete cascade,
  name text not null,
  email text,
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  subscription_status text not null default 'trialing',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null,
  email text,
  phone text,
  job text not null,
  notes text,
  value numeric(12,2) not null default 0,
  status text not null default 'new' check (status in ('new','contacted','quote_sent','viewed','accepted','declined','won','lost')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quotes (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  lead_id uuid references public.leads(id) on delete set null,
  number bigint generated by default as identity unique,
  public_token uuid not null default gen_random_uuid() unique,
  customer_name text not null,
  customer_email text,
  job text not null,
  notes text,
  status text not null default 'draft' check (status in ('draft','sent','viewed','accepted','declined','expired')),
  subtotal numeric(12,2) not null default 0,
  tax numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  sent_at timestamptz,
  viewed_at timestamptz,
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quote_items (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references public.quotes(id) on delete cascade,
  description text not null,
  quantity numeric(12,2) not null default 1,
  unit_price numeric(12,2) not null default 0,
  amount numeric(12,2) generated always as (quantity * unit_price) stored
);

create table if not exists public.activity (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  type text not null,
  message text not null,
  quote_id uuid references public.quotes(id) on delete set null,
  lead_id uuid references public.leads(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists leads_business_id_idx on public.leads(business_id, created_at desc);
create index if not exists quotes_business_id_idx on public.quotes(business_id, created_at desc);
create index if not exists quote_items_quote_id_idx on public.quote_items(quote_id);
create index if not exists activity_business_id_idx on public.activity(business_id, created_at desc);

alter table public.businesses enable row level security;
alter table public.leads enable row level security;
alter table public.quotes enable row level security;
alter table public.quote_items enable row level security;
alter table public.activity enable row level security;

drop policy if exists businesses_owner_all on public.businesses;
create policy businesses_owner_all on public.businesses for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());

drop policy if exists leads_owner_all on public.leads;
create policy leads_owner_all on public.leads for all using (business_id in (select id from public.businesses where owner_id = auth.uid())) with check (business_id in (select id from public.businesses where owner_id = auth.uid()));

drop policy if exists quotes_owner_all on public.quotes;
create policy quotes_owner_all on public.quotes for all using (business_id in (select id from public.businesses where owner_id = auth.uid())) with check (business_id in (select id from public.businesses where owner_id = auth.uid()));

drop policy if exists quote_items_owner_all on public.quote_items;
create policy quote_items_owner_all on public.quote_items for all using (quote_id in (select q.id from public.quotes q join public.businesses b on b.id=q.business_id where b.owner_id=auth.uid())) with check (quote_id in (select q.id from public.quotes q join public.businesses b on b.id=q.business_id where b.owner_id=auth.uid()));

drop policy if exists activity_owner_all on public.activity;
create policy activity_owner_all on public.activity for all using (business_id in (select id from public.businesses where owner_id = auth.uid())) with check (business_id in (select id from public.businesses where owner_id = auth.uid()));

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists businesses_touch on public.businesses; create trigger businesses_touch before update on public.businesses for each row execute function public.touch_updated_at();
drop trigger if exists leads_touch on public.leads; create trigger leads_touch before update on public.leads for each row execute function public.touch_updated_at();
drop trigger if exists quotes_touch on public.quotes; create trigger quotes_touch before update on public.quotes for each row execute function public.touch_updated_at();

create or replace function public.create_business_for_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.businesses(owner_id,name,email) values(new.id,coalesce(new.raw_user_meta_data->>'business_name','My Business'),new.email) on conflict (owner_id) do nothing; return new; end $$;
drop trigger if exists on_auth_user_created_business on auth.users;
create trigger on_auth_user_created_business after insert on auth.users for each row execute function public.create_business_for_user();
