'use client'
import {useEffect,useState} from 'react'
import {useRouter} from 'next/navigation'
import {createClient} from '@/lib/supabase/client'

type Lead={id:string,name:string,job:string,value:number,status:string}
export default function Dashboard(){
 const supabase=createClient(),router=useRouter();const[user,setUser]=useState<any>(null),[biz,setBiz]=useState<any>(null),[leads,setLeads]=useState<Lead[]>([]),[tab,setTab]=useState('overview'),[loading,setLoading]=useState(true),[modal,setModal]=useState(false),[name,setName]=useState(''),[job,setJob]=useState(''),[value,setValue]=useState('')
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/auth?mode=signin');return}setUser(user);let{data:b}=await supabase.from('businesses').select('*').eq('owner_id',user.id).single();if(!b){const r=await supabase.from('businesses').insert({owner_id:user.id,name:user.user_metadata?.business_name||'My Business',email:user.email}).select().single();b=r.data}setBiz(b);if(b){const r=await supabase.from('leads').select('*').eq('business_id',b.id).order('created_at',{ascending:false});setLeads(r.data||[])}setLoading(false)})()},[])
 async function addLead(){if(!name||!job||!biz)return;const r=await supabase.from('leads').insert({business_id:biz.id,name,job,value:Number(value)||0}).select().single();if(r.data)setLeads(x=>[r.data,...x]);setName('');setJob('');setValue('');setModal(false)}
 async function signOut(){await supabase.auth.signOut();router.replace('/')}
 async function checkout(){const r=await fetch('/api/checkout',{method:'POST'});const d=await r.json();if(d.url)location.href=d.url;else alert(d.error||'Billing is not configured yet.')}
 if(loading)return <div className="dashLoading">Loading QuoteFlow…</div>
 const pipeline=leads.reduce((s,l)=>s+Number(l.value||0),0)
 const menu=['overview','leads','quotes','customers','reports','settings']
 return <main className="dashboardPage"><header className="dashTop"><a className="brand" href="/">quote<span>flow</span></a><div><b>{biz?.name}</b><button onClick={signOut}>Sign out</button></div></header><div className="dashLayout"><aside className="dashSide">{menu.map(x=><button className={tab===x?'active':''} key={x} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}<div className="sidePlan"><small>PLAN</small><b>{biz?.subscription_status==='active'?'Pro':'Trial'}</b><button onClick={checkout}>Manage billing</button></div></aside><section className="dashContent">
 {tab==='overview'&&<><Head title="Overview" text="Here's what needs your attention today." action="+ New lead" onAction={()=>setModal(true)}/><Cards pipeline={pipeline} leads={leads}/><Panel title="Recent leads">{leads.slice(0,8).map(l=><LeadRow key={l.id} lead={l}/>)}{!leads.length&&<Empty/>}</Panel></>}
 {tab==='leads'&&<><Head title="Your opportunities." text="Every potential job, in one place." action="+ Add lead" onAction={()=>setModal(true)}/><Panel title="All leads">{leads.map(l=><LeadRow key={l.id} lead={l}/>)}{!leads.length&&<Empty/>}</Panel></>}
 {tab==='quotes'&&<><Head title="Your quotes." text="Quotes will live here as you create them." action="+ New quote" onAction={()=>alert('The quote editor API is wired next.')}/><Panel title="Quotes"><Empty text="No quotes yet. Create a lead, then create a quote from it."/></Panel></>}
 {tab==='customers'&&<><Head title="Your customers." text="Customer records connected to your leads."/><Panel title="Customers">{Array.from(new Map(leads.map(l=>[l.name,l])).values()).map(l=><LeadRow key={l.id} lead={l}/>)}{!leads.length&&<Empty/>}</Panel></>}
 {tab==='reports'&&<><Head title="Your numbers." text="A simple view of your pipeline."/><Cards pipeline={pipeline} leads={leads}/></>}
 {tab==='settings'&&<><Head title="Your workspace." text="Business details and subscription."/><div className="settings"><label>BUSINESS NAME<input value={biz?.name||''} onChange={e=>setBiz({...biz,name:e.target.value})}/></label><label>ACCOUNT EMAIL<input value={user?.email||''} disabled/></label><button className="primaryAction" onClick={async()=>{await supabase.from('businesses').update({name:biz.name}).eq('id',biz.id);alert('Saved.')}}>Save changes</button></div></>}
 </section></div>{modal&&<div className="overlay"><div className="newModal"><button className="modalX" onClick={()=>setModal(false)}>×</button><small>NEW LEAD</small><h2>Add an opportunity.</h2><label>Customer<input value={name} onChange={e=>setName(e.target.value)} placeholder="Sarah Mitchell"/></label><label>Job<input value={job} onChange={e=>setJob(e.target.value)} placeholder="Roof repair"/></label><label>Estimated value<input value={value} onChange={e=>setValue(e.target.value)} placeholder="4850"/></label><button className="primaryAction full" onClick={addLead}>Create lead →</button></div></div>}</main>
}
function Head({title,text,action,onAction}:{title:string,text:string,action?:string,onAction?:()=>void}){return <div className="dashHeading"><div><small>QUOTEFLOW</small><h1>{title}</h1><p>{text}</p></div>{action&&<button className="primaryAction" onClick={onAction}>{action}</button>}</div>}
function Cards({pipeline,leads}:{pipeline:number,leads:Lead[]}){const hot=leads.filter(l=>l.value>=5000).length;return <div className="dashCards"><div><small>OPEN PIPELINE</small><b>${pipeline.toLocaleString()}</b><span>Across active leads</span></div><div><small>TOTAL LEADS</small><b>{leads.length}</b><span>In your pipeline</span></div><div><small>HOT OPPORTUNITIES</small><b>{hot}</b><span>$5k+ potential</span></div><div><small>AVERAGE VALUE</small><b>${leads.length?Math.round(pipeline/leads.length).toLocaleString():'0'}</b><span>Per lead</span></div></div>}
function Panel({title,children}:{title:string,children:React.ReactNode}){return <div className="dashPanel"><div className="panelTitle"><b>{title}</b></div>{children}</div>}
function LeadRow({lead}:{lead:Lead}){return <div className="leadItem"><div className="leadAvatar">{lead.name.slice(0,2).toUpperCase()}</div><div><b>{lead.name}</b><small>{lead.job}</small></div><strong>${Number(lead.value).toLocaleString()}</strong><em>{lead.status.replace('_',' ')}</em></div>}
function Empty({text='No leads yet. Add your first opportunity above.'}){return <div className="empty">{text}</div>}
